multi-build/multibuild

.travis.yml, osx_utils.sh, tests/test_fill_pyver.sh
Python 3.6 also becomes the default for Python specified as '3', for OSX.
=> MRG: try adding Python 3.6, for OSX.

common_utils.sh, tests/test_fill_submodule.sh, tests/test_multibuild.sh, tests/utils.sh
pip will copy the directory it installs from before running the install
/ wheel build.  If the directory is a submodule, then the copy breaks
the connection with the containing project, so git commands to get the
version will fail.
Fix is to re-create the .git directory for submodules.
Version of fix in https://github.com/matthew-brett/multibuild/pull/12
with thanks to Hassan Kibirige for doing the hard work of diagnosis and finding the general solution.
=> MRG: make submodule .git directory for versioneer

ci/appveyor/install.ps1
This eliminates the need to bump the version manually on new Miniconda releases.
=> Use latest Miniconda distribution on Appveyor

library_builders.sh
Some libraries use 'tar.bz2' instead of 'tar.gz' as source archive format.
This patch allows to pass a fourth argument to `build_simple` function to specify an alternative extension to the default `tar.gz`.
The `untar` function in common_utils.sh, used by `fetch_unpack`, already supports the following archive formats: tar, gz, bz2, zip and xz.
=> [library_builders] allow to override tar.gz extension in build_simple

library_builders.sh
For [2.1.0](https://github.com/uclouvain/openjpeg/releases/tag/version.2.1) and prior, [the archives started with 'version.'](https://github.com/uclouvain/openjpeg/archive/version.2.1.tar.gz).
Since then, [they start with 'v'](https://github.com/uclouvain/openjpeg/archive/v2.1.1.tar.gz) - https://github.com/uclouvain/openjpeg/releases
=> Changed openjpeg archive prefix for versions newer than 2.1.0

common_utils.sh, tests/test_fill_pypy_ver.sh, tests/test_multibuild.sh
Add tests for fill of pypy versions, give full versions for latest.
Question - what should happen for:
```
fill_pypy_ver 3
fill_pypy_ver 2.1
```
etc - where there is no matching pypy version?
=> WIP: add tests for PyPy fill code

ci/appveyor/install.ps1
The URL for Python 2.x miniconda has been changed to ``http://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86.exe``. As a result, my Windows builds ended up crashing:
```
rd /s /q %PYTHON%
.\\multibuild\\ci\\appveyor\\install.ps1
Installing Python 2.7 for 32 bit architecture to C:\Miniconda
Downloading Miniconda-latest-Windows-x86.exe from http://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86.exe
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At C:\projects\treelite-wheels\multibuild\ci\appveyor\install.ps1:40 char:8
+        $webclient.DownloadFile($url, $filepath)
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ …
```
=> Update URL for Python 2.x Miniconda

library_builders.sh, tests/test_library_builders.sh
Here, we add the option to pass arbitrary configure arguments to build-simple. In addition, we add a function that improves the testing of library builders by reducing the verbosity of testing unless there are test failures. We then test our new functions by adding them to the build_libraries tests.
=> libraries: allow build_simple with configure args

tests/test_library_builders.sh, travis_steps.sh
This is a version of https://github.com/matthew-brett/multibuild/pull/67 . That
pull request broke scipy builds because it sets LDFLAGS, which numpy uses in an
inconvenient way - see https://github.com/matthew-brett/multibuild/issues/76
for discussion.
=> WIP: Try using LIBRARY_PATH to catch built libs

library_builders.sh
This can fix in certain scenarios where the tag name is prefixed with "v".
=> [libraries] attempt to fix build-github

README.rst, docker_build_wrap.sh, docker_test_wrap.sh, travis_linux_steps.sh, travis_osx_steps.sh
I usually like to check-in `multibuild` as a git submodule inside my projects rather than creating a separate wheel builder git repostory.
And I also like to keep all the CI-related scripts and config files in a separate subfolder (e.g. `ci`), to avoid cluttering the root of the repository with files that are not normally needed and may confuse other developers.
This PR allows to set a `$CONFIG_PATH` environment variable with the location of the "config.sh" file.
The current behaviour doesn't change (it's an opt-in kind of feature).
Please let me know what you think, thanks.
=> Allow to specify a custom $CONFIG_PATH for config.sh

travis_linux_steps.sh
Use case: if there are multiple libs to build from source. Used in https://github.com/skvark/opencv-python (see https://github.com/skvark/opencv-python/pull/58#issuecomment-352496235 ).
=> Customize Docker build image

README.rst
=> remove references to python 2.6 in README.rst

osx_utils.sh
delocate-listdeps is not required and can take several minutes for
heavyweight wheels.
Closes #124.
=> macOS: drop call to delocate-listdeps for speedup

.travis.yml, tests/test_library_builders.sh
https://travis-ci.org/matthew-brett/multibuild/jobs/329985249#0-2249 :
/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! You're running 2.0.0. (RuntimeError)
This may even be the reason for the build's failure.
https://docs.travis-ci.com/user/reference/osx/#Homebrew recommends to only run `brew update` if you must.
=> In xcode 6.4, `brew update' breaks `brew' due to old `ruby'.

configure_build.sh
Directly strip the binaries on compilation. Additionally I will have a look into integrating stripping into `auditwheel` but this change will prevent persisting the symbols in the first place. The savings are quite large here, e.g. for Pandas the sizes change 27M wheel and 104M unpacked on disk to a 11M wheel and 44M unpacked on disk. These saving are significantly visible in e.g. docker images that contain the unpacked binaries.
Verified with several packages as we had seen problems with this in the past:
* `Pandas` https://travis-ci.org/xhochy/pandas-wheels/builds/337220847
* `Cython` (2.6 builds fail as this version is no longer in the image) https://travis-ci.org/xhochy/cython-wheels/builds/337244795
* `h5py` https://travis-ci.org/xhochy/h5py-wheels/builds/337245000
* `matplotlib` …
=> Strip binaries on non-OSX builds

docker_build_wrap.sh
Change directory early, and therefore avoid kludgy /io trick for env_vars.sh.
Doesn't change behavior, but does make environment more specific (operating in
repo directory) for the build script.
=> MRG: Refactor fix to env_vars.sh location

library_builders.sh
I think getting this merged, or at least on a branch in this repository, is a pre-requsite for building h5py wheels with 1.10.
Not really sure how to test this, I verified in a local shell that this produces the correct URL.
=> ENH: bump the hdf5 version

library_builders.sh
Removed trailing slashes in build_simple urls, since they otherwise become double slashes in the URL - https://github.com/matthew-brett/multibuild/blob/devel/library_builders.sh#L66
=> Removed trailing slashes in build_simple urls

travis_linux_steps.sh
Nipy server's certificate is out of date, switch to using Rackspace
container instead.
I've gone through the files available at http://nipy.bic.berkeley.edu/manylinux
- and I think the Rackspace container has all the ones we care about.  I
suggest we merge here and wait for complaints.
=> Update manylinux URL

.travis.yml
Perhaps there is a reason for specifying the micro Python versions, but something like 2.7.11 is no longer the latest version. It could be changed to 2.7.15, or, as in this PR, supplying the version [as 2.7 instead allows it to be kept up-to-date automatically](https://docs.travis-ci.com/user/languages/python/#Specifying-Python-versions).
=> Removed micro Python version specification in Travis

.appveyor.yml, install_python.ps1
Powershell script to download and install a new version of Python, if not
present on the Appveyor image.
This should make it easier to get out wheels after a Python release.
=> Add script to install new Python on Appveyor

common_utils.sh, library_builders.sh
The bzip.org website seems to have gone down and has a sitter there.
Also, make unzipping quiet to get the output directory back.
=> MRG: fixes for bzip website; noisy zip unpacking

osx_utils.sh
Fixes [job that has been failing](https://travis-ci.org/matthew-brett/multibuild/jobs/443785039) since pip 18.0 dropped support for Python 3.3
=> Use Python 3.3 variant of get-pip.py

.travis.yml, README.rst, manylinux_utils.sh, osx_utils.sh, tests/test_fill_pyver.sh, tests/test_manylinux_utils.sh, tests/test_osx_utils.sh
Python 3.3 has been EOL since 2017-09-29, and has already been dropped by manylinux: 
https://github.com/pypa/manylinux/pull/188
=> Drop support for EOL Python 3.3

common_utils.sh
In https://github.com/python-pillow/Pillow-wheels, `TEST_DEPENDS="pytest pytest-cov numpy scipy"`. scipy depends on numpy, and so if you try to install scipy and numpy at the same time, you receive an error that numpy is not present - https://travis-ci.org/python-pillow/pillow-wheels/jobs/397965939#L4956. This is not normally the case - it would seem to be happening here because wheels do not yet exist for Python 3.7.
So instead, for this scenario, I suggest installing TEST_DEPENDS packages one at a time.
Note that this doesn't solve that pillow-wheels build completely, but it's a step in the right direction, and worthwhile as a change in it's own right.
=> Changed TEST_DEPENDS pip install to install one package at a time

library_builders.sh
The bzip site is back, but instructs you to download bzip from SourceForge - http://www.bzip.org/downloads.html
=> Updated bzip URL

.travis.yml, README.rst
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
=> sudo no longer required

common_utils.sh
See what you think of this - clean up the temporary directory 'tmp_for_test' at the end of `install_run` if no files are left inside.
=> Remove temporary directory if empty

.travis.yml
As seen at https://travis-ci.org/matthew-brett/multibuild/jobs/454975750
> Running builds with Xcode 6.4 in Travis CI is deprecated and will be removed in January 2019. If Xcode 6.4 is critical to your builds, please contact our support team at support@travis-ci.com to discuss options.
=> Removed Xcode 6.4 builds from Travis CI

library_builders.sh, travis_osx_steps.sh
Since https://github.com/travis-ci/travis-build/commit/52c6b6cc1d537e52c8ae6f0906944d6fcaa3d173, it's no longer needed
and may trigger stuff like [unnecessary `git clone`s](https://travis-ci.org/skvark/opencv-python/jobs/569294041#L2310).
=> Remove "remove OCLint" workaround

common_utils.sh
Fixes https://github.com/matthew-brett/multibuild/issues/259.
=> Rename 'gh-clone' to fix bash error on MacOS

.travis.yml, manylinux_utils.sh, osx_utils.sh
related to gh-261
CPython no longer adds 'm' to the abi tag after  pypa/wheel#303 for python 3.8 and up
=> remove 'm' from python path for 3.8 and up

library_builders.sh
Build HDF5 with --enable-thread-safe flag.
This was brought to my attention by @ZanSara over at pytables/pytables#776
It seems a good idea to enable thread safety for the HDF5 library.
This makes a lot of sense, as the conda-forge [hdf5 package is also build](https://github.com/conda-forge/hdf5-feedstock/blob/master/recipe/build.sh) with this flag.
For reference, the current HDF5 config is:
```
SUMMARY OF THE HDF5 CONFIGURATION
=================================
General Information:
-------------------
HDF5 Version: 1.10.4
Configured on: Mon Oct 28 15:56:36 UTC 2019
Configured by: root@eb93ce3c980d
Host system: x86_64-unknown-linux-gnu
Uname information: Linux eb93ce3c980d 4.4.0-101-generic #124~14.04.1-Ubuntu SMP Fri Nov 10 19:05:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Byte sex: …
```
=> Build HDF5 with thread safety enabled

.travis.yml, osx_utils.sh, tests/test_multibuild.sh, tests/test_osx_utils.sh, tests/test_python_install.sh, tests/test_supported_wheels.sh, travis_osx_steps.sh
This PR does three things:
* Sets the default Python installer / MB_PYTHON_OSX_VER for Python 3.8, so
users don't have do this in their travis.yml files.
* Adds a brew update fix to work round a syntax error on Homebrew on macOS.
* Refactors our .travis.yml to use MB_PYTHON_VERSION, rather than
PYTHON_VERSION.  This matches the way that users will write their travis.yml
files.
=> Set default OSX_VER to 10.9 from Python 3.8

library_builders.sh, tests/test_library_builders.sh
This is embarrassing (ref #274):
travis log: https://api.travis-ci.org/v3/job/606358953/log.txt
```
configure: WARNING: unrecognized options: --enable-thread-safe
```
The flag should be: `--enable-threadsafe`: https://support.hdfgroup.org/HDF5/faq/threadsafe.html
=> Fix typo in --enable-threadsafe flag

.travis.yml, osx_utils.sh, tests/test_multibuild.sh, tests/test_osx_utils.sh, travis_osx_steps.sh
default for MB_PYTHON_OSX_VER changed from 10.6 to 10.9 for MB_PYTHON_VERSION 2.7.15+ and 3.6+. This should mean users dont have to explictly set MB_PYTHON_OSX_VER for normal use cases, as most projects only build the latest.
Also adds a new function `macpython_sdk_list_for_version`which could be useful for validating MB_PYTHON_OSX_VER / MB_PYTHON_VERSION combinations in future, rather than just letting the [python.org](python.org) download fail if an invalid combination is chosen
closes #278
=> set MB_PYTHON_OSX_VER default to the newest available

README.rst, configure_build.sh
add ability for user to override `PLAT` for macOS builds. Prior to this `PLAT` was only used for linux builds. 
closes #252
=> Allow user to override PLAT for macOS builds

library_builders.sh
https://download.sourceforge.net/bzip2/ only has 1.0.6, while https://sourceware.org/pub/bzip2/, as found at https://sourceware.org/bzip2/, has 1.0.1 through 1.0.8.
=> Changed bzip2 download URL

osx_utils.sh, tests/test_fill_pyver.sh, tests/test_manylinux_utils.sh
I was playing with the new 3.8 changes and noticed tests seemed to be incomplete. If someone else is working on this already, my apologies
addresses #261 @mattip
=> Add 3.8 tests for linux + mac, make 3.8 the default for mac

common_utils.sh, supported_wheels.py
As of today, when no supported wheels are found, the program fail with the cryptic message:
```
ERROR: You must give at least one requirement to install (maybe you meant "pip install https://5cf40426d9f06eb7461d-6fe47d9331aba7cd62fc36c7196769e4.ssl.cf2.rackcdn.com"?)
```
As shown in #300 
Even though the underlying issue has been fixed in #298 , I think having a more meaningful error message could help debugging in the future.
=> Warn and exit when no supported wheels are found

.travis.yml, README.rst, common_utils.sh, docker_build_wrap.sh, docker_test_wrap.sh, manylinux_utils.sh, supported_wheels.py, tests/config.sh, tests/test_multibuild.sh, travis_linux_steps.sh
I opened a new github org multi-build to hold recipes for new docker images for testing, and pushed a few to the dockerhub organization "multibuild". This PR adds an option to use them, and modifies 2 CI runs.
If this looks good, I can push more images to docker hub: xenial32 and bionic64, maybe reproduce the trusty ones too?
=> allow choosing the test docker image

tests/test_multibuild.sh
removing `brew update` seems to fix #320  but is there something Im missing here?
why would it only fail on the Xcode8 and Xcode 7.3 images?
=> remove brew update to avoid problems with older macos images

travis_osx_steps.sh
Follow up for #321 that removed the update from the tests.
=> BUG: Remove brew update to avoid problems with older macos

travis_linux_steps.sh
fixes #309 but leaves the option for a MANYLINUX_URL environment variable to be returned from `pip_opts`, which is used when installing `$TEST_DEPENDENCY`  and `$BUILD_DEPENDS` in `common_utils.sh`.
=> make MANYLINUX_URL optional

osx_utils.sh
Minor. `stripped_ver` is only used if `$impl` is `cp`.
=> Do not call strip_macpython_ver_prefix if it is not used

library_builders.sh
Certificate expired - first try using HTTP.
=> MRG: Temporary fix for Ragel build on macOS

.travis.yml, common_utils.sh, tests/test_multibuild.sh, tests/test_python_install.sh
**Minor changes**
- Fixes a typo - "s30x"
- Removes the default `suffix` value, since the default switch case throws an error, so that the default value is never used.
**The main change**
The README states that
> The PLAT environment variable can be one of x86_64, i686 s390x, ppc64le, or aarch64
It doesn't mention "darwin", which `install_pypy` currently checks for. Instead of checking for PLAT at all on macOS, this PR changes to just using IS_OSX.
cc @mattip since they wrote this code and may have thoughts on this
=> Fixes for install_pypy

.travis.yml
devel is currently failing - https://travis-ci.org/github/matthew-brett/multibuild/jobs/750719524 - because Homebrew no longer supports 10.13.
This PR updates Xcode for that job to 10.2, so that macOS is then 10.14 (see https://docs.travis-ci.com/user/reference/osx/#macos-version)
=> Updated Travis job to a macOS supported by Homebrew

README.rst, common_utils.sh, configure_build.sh, library_builders.sh, tests/test_library_builders.sh, tests/test_multibuild.sh
Apple left 'OS X' behind with 10.11, and now we've moved on to 11.
So multibuild's variable `IS_OSX` is not quite as suitable as it once was.
This PR adds `IS_MACOS` - but still sets `IS_OSX` to not break any external scripts that may be using it.
=> Added IS_MACOS

common_utils.sh, docker_build_wrap.sh, osx_utils.sh, tests/test_python_install.sh
Python 2.7 went into pip back-compat mode.
=> MRG: Use back-compatble pip versions for old Python

travis_osx_steps.sh
Originally for #391
That PR suggested replacing
```
if [[ "$(xcrun -show-sdk-version)" == 10.*  ]]; then
```
with
```
function check_sdk_11 {
ver="$(xcrun -show-sdk-version)"
if [[ "${ver}" == "" || "${ver}" == 10.* ]]; then
echo "not found"
else
echo "found"
fi
}
```
This suggests using 
```
if [[ "$(xcrun -show-sdk-version)" -lt 11 ]]; then
```
instead.
Testing on my local, here's how it behaves.
```
$ if [[ "10" -lt 11 ]]; then echo "not found"; else echo "found"; fi
not found
$ if [[ "" -lt 11 ]]; then echo "not found"; else echo "found"; fi 
not found
$ if [[ "11" -lt 11 ]]; then echo "not found"; else echo "found"; fi
found
$ if [[ "12" -lt 11 ]]; then echo "not found"; else echo "found"; fi
found
```
It's simpler, and I believe, clearer.
=> Simplified code

README.rst
"arm64" and "universal2" are documented in the README as possible PLAT values
> For Apple silicon support you can either create an ``arm64`` wheel or a ``universal2`` wheel by supplying ``PLAT`` env variable.
This adds those values to the earlier list of all possible values.
=> Added "arm64" and "universal2" as possible PLAT values

.travis.yml, common_utils.sh, osx_utils.sh, tests/test_common_utils.sh, tests/test_multibuild.sh
probably means a bad python version was specified
add an ‘expected fail’ test to the matrix to exercise this case
closes #293
=> Friendly error when curl HTTP errors downloading macOS python

osx_utils.sh
This script was moved to a new URL, and the old URL returns a script
which just prints an error message pointing to the new location.
=> Updated get-pip.py URL for Python 3.5

tests/test_library_builders.sh
Since manylinux_2_24 wheels are still unavailable at https://anaconda.org/multibuild-wheels-staging/openblas-libs/files
Previously discussed in https://github.com/matthew-brett/multibuild/pull/396#issuecomment-813307265
=> Do not test build_openblas on manylinux_2_24

osx_utils.sh, tests/test_python_install.sh
You can see that there are two jobs failing in the first commit, where I just upgrade the Python versions. The error is ["The 'pip==19.3.1' distribution was not found and is required by the application"](https://travis-ci.org/github/matthew-brett/multibuild/jobs/771532262#L712).
I conclude that this is because there hasn't been a pip release since the release of these Python versions. This means that [pip isn't newly installed](https://travis-ci.org/github/matthew-brett/multibuild/jobs/771532262#L673-L674), meaning that ``pip install "setuptools>=25" `` doesn't have the global link to pip in the same way.
So instead, I've changed the first line of
https://github.com/matthew-brett/multibuild/blob/45d97819e7d39dd2264b2c3cd353c26c4e1ebb74/tests/test_python_install.sh#L11-L12
to use …
=> Updated Python versions

common_utils.sh, library_builders.sh, tests/test_common_utils.sh, tests/test_library_builders.sh
Continuation of #380
As established that PR, [`unxz -c $in_fname | tar -xf -`](https://github.com/radarhere/multibuild/commit/8d400c0356cc), passes [on Linux, but fails on macOS](https://travis-ci.org/github/radarhere/multibuild/builds/771016908).
[As has been pointed out](https://github.com/matthew-brett/multibuild/pull/380#discussion_r554427716), a simpler option would be [`tar -xf $in_fname`](https://github.com/radarhere/multibuild/commit/1bc54c77e29a335b3c010d7f8608b7c85a8fa25b), which passes with my test [on both Linux and macOS.](https://travis-ci.org/github/radarhere/multibuild/builds/771017020)
If I [move my test into test_library_builders.sh though](https://github.com/radarhere/multibuild/commit/d7f1f44a4f659970f5cf0e82f4faecf33e927a5d), so that it is run within …
=> Fixed untar for .xz

osx_utils.sh
cc @radarhere 
This fixes an issue introduced in #409
=> Use 11.0 installer only on arm64 hardware

README.rst
Corrects three instances in the README where links are not rendering as intended.
=> Corrected README formatting

osx_utils.sh, tests/test_fill_pyver.sh
Adds Python 3.10 for https://github.com/matthew-brett/multibuild/issues/421
=> Added Python 3.10

common_utils.sh, configure_build.sh, library_builders.sh, travis_linux_steps.sh
Given that manylinux1 and manylinux2010 are EOL, this PR suggests updating the default to 2014.
https://github.com/pypa/manylinux
- manylinux2014 (CentOS 7 based)
...
- manylinux2010 (CentOS 6 based - EOL)
...
- manylinux1 (CentOS 5 based - EOL)
...
Support for manylinux1 will end on January 1st, 2022.
=> Updated default manylinux version to 2014

tests/test_library_builders.sh
`ensure_xz` is a dependency of `build_tiff`
https://github.com/matthew-brett/multibuild/blob/c395b10e8395d43b51209760dc0853303ecfcd9e/library_builders.sh#L148-L153
However, `build_tiff` is currently tested before `ensure_xz`. So if `ensure_xz` were to fail, it would appear as part of the `build_tiff` test, rather than failing on it's own.
Similarly, `build_tiff` is a dependency of `build_libwebp`
https://github.com/matthew-brett/multibuild/blob/4e24f8228277dd7398d95bf43e2cb6eb7eb1f029/library_builders.sh#L197-L204
Yet `build_libwebp` is currently tested before `build_tiff`.
So this PR rearranges items so that the dependencies are tested by themselves first.
=> Test dependencies by themselves first

.github/workflows/test.yml
Related to #434 and #435
~Failing AppVeyor job is fixed in #429~
=> GitHub Actions: Do we want an OS and Python build matrix?

common_utils.sh, docker_test_wrap.sh, library_builders.sh, manylinux_utils.sh, travis_linux_steps.sh
musllinux spec landed, let's get these wheels rollin 😎
=> musllinux support

configure_build.sh, library_builders.sh
After #430,
- Use apk instead of yum when installing wget in configure_build.sh
- Redirect stdout when installing cmake on Alpine in `get_modern_cmake`, to prevent the stdout from becoming part of the response
=> Fixed installing cmake and wget on Alpine

.github/workflows/test.yml
https://github.com/actions/checkout/releases
https://github.com/actions/setup-python/releases
=> Upgrade actions/checkout and actions/setup-python

.github/workflows/lint_python.yml, README.rst, supported_wheels.py
GHA may be a bit easier to work with than AppVeyor
Test results: https://github.com/cclauss/multibuild/actions
=> GitHub Action to lint Python code

README.rst
Updated the README to match the current default.
https://github.com/multi-build/multibuild/blob/a05e8f2eb71304eaf1187a68e36b8ceebf091fb7/common_utils.sh#L27-L28
=> Updated README after default MB_ML_VER changed in #423

common_utils.sh
The MB_ML_VER default is currently 2014.
https://github.com/multi-build/multibuild/blob/a05e8f2eb71304eaf1187a68e36b8ceebf091fb7/common_utils.sh#L27-L28
This is a valid default for manylinux. For musllinux though, "_1_1" would be better.
This PR sets the default depending on whether MB_ML_LIBC is manylinux or musllinux.
=> Set relevant MB_ML_VER default for musllinux

library_builders.sh, tests/test_library_builders.sh
This PR suggests adding `build_libjpeg_turbo`.
This is an alternative to libjpeg, so rather than touching "jpegturbo-stamp" or similar, it touches "jpeg-stamp", just as `build_jpeg` does. This means that if a user ran `build_libjpeg_turbo`, and then `build_tiff` (which internally calls `build_jpeg`), libjpeg would not be built, because libjpeg turbo was already in place.
=> Added build_libjpeg_turbo

README.rst, travis_linux_steps.sh
Use Focal test image by default.
Stick to Trusty for 32-bit (we don't have a 32-bit Focal image).
=> Change default test image for 64-bit

travis_linux_steps.sh
After https://github.com/multi-build/docker-images/pull/29, and seen at https://hub.docker.com/r/multibuild/alpine3.15_x86_64, we can now use Alpine 3.15.
=> Updated to Alpine 3.15 test image

library_builders.sh
We had lots of timeouts connecting to https://sourceware.org during yesterday's Pillow release, and just one in a batch of ~25 wheel builds meant the whole 45 min build needed restarting (https://github.com/python-pillow/pillow-wheels/issues/276).
About 8/10 of the failures were sourceware timeouts ([3](https://github.com/python-pillow/pillow-wheels/actions/runs/2075952528) + [7](https://github.com/python-pillow/pillow-wheels/actions/runs/2076994216)).
Sourceware themselves say:
> These sites mirror the free software ftp directory directly. The master sourceware.org server itself is usually overloaded.
https://sourceware.org/mirrors.html
So let's use a mirror here too.
=> Use mirror instead of flaky sourceware.org

travis_linux_steps.sh
Use `$plat` when selecting default focal `DOCKER_TEST_IMAGE`, rather than just selecting `x86_64`.
=> Use $plat when selecting default focal DOCKER_TEST_IMAGE

travis_linux_steps.sh
When `install_run` replaces "aarch64" with "arm64v8", it should do so when `$plat` matches, not just `$PLAT`.
This then includes the scenario where the user passes in the value as the first argument to `install_run`, not just using the global `$PLAT`.
=> Replace aarch64 with arm64v8 for default focal DOCKER_TEST_IMAGE

README.rst
manylinux have released _2_28 images - https://github.com/pypa/manylinux#manylinux_2_28-almalinux-8-based
=> manylinux have released _2_28 images

library_builders.sh
giflib >= 5.1.5 no longer has a 'configure' file.
This is noted in https://github.com/nesbox/giflib/blob/master/NEWS
> The horrible old autoconf build system has been removed with extreme prejudice. 
> You now build this simply by running "make" from the top-level directory.
So if the giflib verison is >= 5.1.5, this PR runs a modified version of build_simple that skips the `./configure` step.
=> Skip configure in giflib if version >= 5.1.5

library_builders.sh
Updated default libpng from 1.6.21 to 1.6.37, to avoid a vulnerability
http://www.libpng.org/pub/png/libpng.html
> libpng versions 1.6.36 and earlier have a use-after-free bug in the simplified libpng API png_image_free(). It has been assigned ID CVE-2019-7317. The vulnerability is fixed in version 1.6.37, released on 15 April 2019.
=> Updated libpng to 1.6.37

common_utils.sh
When building wheels, it wasn't able to find the latest tags: https://github.com/pyproj4/pyproj-wheels/runs/4961483736?check_suite_focus=true
This fixed the issue.
=> Fetch tags in clean_code

README.rst, osx_utils.sh
RC1 is the latest with RC2 due on Monday: https://peps.python.org/pep-0664/
And add 3.11 to the README.
=> Update 3.11.0 to RC1

library_builders.sh
As stated in https://pcre.org/, PCRE has been moved to sourceforge and the old FTP is no longer available.
=> Fix pcre download

common_utils.sh
PyPy 7.3.10 has been released - https://www.pypy.org/posts/2022/12/pypy-v7310-release.html
At https://downloads.python.org/pypy/, the new release includes 
- pypy3.8-v7.3.10-macos_x86_64.tar.bz2
rather than 7.3.9's
- pypy3.8-v7.3.9-osx64.tar.bz2
So this PR uses the version to set the suffix.
=> Updated the latest PyPy version

travis_linux_steps.sh
Similar to #469, except now for alpine, after https://github.com/multi-build/docker-images/pull/38 added an alpine arm64v8 image.
=> Replaced aarch64 with arm64v8 for default alpine DOCKER_TEST_IMAGE

.github/workflows/lint_python.yml
lint_python is currently failing for devel - https://github.com/multi-build/multibuild/actions/runs/4058339482
Upgrading setuptools fixes it.
=> Upgrade setuptools in lint build

osx_utils.sh
When appending to ARCHFLAGS. Otherwise it's easy to see clang fail because of `-arch arm64-arch arm64`.
=> Add one space in macos_arm64_native_build_setup

osx_utils.sh
Two suggested changes when building universal2 wheels.
1. Instead of presuming the length of the string to replace in the following code, use `sed`. This will allow `$py_osx_ver` to vary in length.
https://github.com/multi-build/multibuild/blob/2e10577a0c2fd2b0d36b3d96dc5c273d2df20698/osx_utils.sh#L513-L514
2. When building for universal2 on x86-64, run the cross build first and then the native build. This will mean that the more natural native variables are in place when the code is finished, for anything that might run afterwards.
=> universal2 build improvements

osx_utils.sh
When searching for wheels to fuse, multibuild currently uses `MB_PYTHON_OSX_VER` to search for the wheels that were built.
https://github.com/multi-build/multibuild/blob/c0a319a5358538b1bf561908f740b24999c76370/osx_utils.sh#L508-L516
I think this should be `MACOSX_DEPLOYMENT_TARGET` instead.
To demonstrate, I've created a simplified branch of pillow-wheels - https://github.com/radarhere/pillow-wheels/tree/demo.
All it does to set the macOS version for the wheels is [`export MACOSX_DEPLOYMENT_TARGET="10.10"`](https://github.com/radarhere/pillow-wheels/blob/41818530935e7fa165f4fdc288d79da95c3b2130/.github/workflows/build.sh#L1)
Without this change, there is [no universal2 wheel at the end of a build.](https://github.com/radarhere/pillow-wheels/actions/runs/4084005956/jobs/7040196343#step:4:1 …
=> Use MACOSX_DEPLOYMENT_TARGET when searching for wheels to fuse

library_builders.sh
When I added `build_libjpeg_turbo` in #454, I wrote out the `CMAKE_INSTALL_PREFIX` as `/usr/local`, rather than `$BUILD_PREFIX`, like `build_openjpeg` and `build_blosc`. This PR corrects that.
This is cherry-picked from #501
=> Use $BUILD_PREFIX in build_libjpeg_turbo

common_utils.sh
`install_wheel` calls supported_wheels.py
https://github.com/multi-build/multibuild/blob/07f10c3439d6e892c030efcc0884b608679766c2/common_utils.sh#L447-L448
and supported_wheels.py imports `wheel`
https://github.com/multi-build/multibuild/blob/07f10c3439d6e892c030efcc0884b608679766c2/supported_wheels.py#L11-L15
However, in Python 3.12 I get
```
Traceback (most recent call last):
File "/io/multibuild/supported_wheels.py", line 12, in <module>
from wheel.install import WHEEL_INFO_RE as wheel_matcher
ModuleNotFoundError: No module named 'wheel'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/io/multibuild/supported_wheels.py", line 14, in <module>
from wheel.wheelfile import WHEEL_INFO_RE
ModuleNotFoundError: No module named …
```
=> Ensure wheel is installed before import

travis_linux_steps.sh
In `build_multilinux`, I would expect `repo_dir` to be uppercase, referring to the environment variable, rather than lowercase, referring to a non-existent local variable.
https://github.com/multi-build/multibuild/blob/4eb855680308fd279357896dfe0afe59e5c307fa/travis_linux_steps.sh#L66-L104
A local `repo_dir` variable was originally added in https://github.com/multi-build/multibuild/commit/09555a6b74133c3f580def75a874d4182643c2d9, but was effectively removed in https://github.com/multi-build/multibuild/commit/3998141
=> Changed repo_dir variable to be uppercase

osx_utils.sh
meson-python does not like duplicate ARCHFLAGS values, and will error
with output such as:
```
('\x1b[31m',)meson-python: error: Multi-architecture builds are not
supported but $ARCHFLAGS='-arch x86_64 -arch x86_64'
[end of output]
```
https://github.com/nipy/nipy-wheels/actions/runs/6805528295/job/18505232990#step:4:164
at time of writing.
=> Only add wrapped archflags if not already present.

travis_linux_steps.sh, travis_osx_steps.sh, travis_steps.sh
We seem to need virtualenv on the Github runners - ensure.
Install tomli by default on local python, to allow pyproject.toml parsers to
fetch requirements etc.
=> MRG: Add tomli, ensure virtualenv

osx_utils.sh, tests/test_fill_pyver.sh
Python 3.13.0 is now in release candidate phase, which makes it ABI stable. This PR adds the [first release candidate](https://pythoninsider.blogspot.com/2024/08/python-3130-release-candidate-1-released.html).
This PR follows the changes in last year's PR:
- https://github.com/multi-build/multibuild/pull/505.
**Edit:** And, like last year, an update to the docker-images:
- https://github.com/multi-build/docker-images/pull/47
=> Add Python 3.13 release candidate 1

.github/workflows/lint_python.yml
As noted in #499 and #497, safety has very limited value. It is now detecting a disputed vulnerability in one of its own dependencies. It is time to disable it.
=> remove noisy inaccurate safety check from linting

library_builders.sh
The default behavior of cmake is to build and install a library with the library's install_name set to `@rpath/libname.dylib`. While this is a good default when the library is being used in an executable, it's a problem on macOS when the library is being used as a dependency in a wheel, because the `@rpath` can't be resolved as part of the delocate process.
Libraries build with autotools/configure (or manually constructed makefiles) aren't affected by this; their default install name is the full install path unless specifically configured with an installation name. 
The libblosc build instruction already included a workaround to explicitly set the library identifiers; it's possible to replace that workaround with an explicit cmake configuration.
In addition, the `CMAKE_INSTALL_LIBDIR` …
=> Ensure cmake-compiled libraries aren't installed with an rpath

.github/workflows/lint_python.yml, supported_wheels.py
Replace bandit, black, flake8, flake8-2020, flake8-bugbear, flake8-comprehensions, isort, and pyupgrade with ruff.
https://docs.astral.sh/ruff
> Ruff can be used to replace [Flake8](https://pypi.org/project/flake8/) (plus dozens of plugins), [Black](https://github.com/psf/black), [isort](https://pypi.org/project/isort/), [pydocstyle](https://pypi.org/project/pydocstyle/), [pyupgrade](https://pypi.org/project/pyupgrade/), [autoflake](https://pypi.org/project/autoflake/), and more, all while executing tens or hundreds of times faster than any individual tool.
=> Format and lint Python code with ruff

library_builders.sh
#531 stated that
> the `CMAKE_INSTALL_LIBDIR` value used for libjpeg-turbo is redundant, as the `/lib` suffix will be implied from the `CMAKE_INSTALL_PREFIX` value.
However, testing the [updated multibuild with Pillow](https://github.com/radarhere/Pillow/commit/2ae0b1c4d15c19d297dd45ba12a66a1734d07c7a), I find that [a job starts failing](https://github.com/radarhere/Pillow/actions/runs/11479693993/job/31946521238).
If I [restore `CMAKE_INSTALL_LIBDIR`](https://github.com/radarhere/multibuild/commit/654dbebc3a5a8173e4f391ed50b17ed69c8284a6) and [test that](https://github.com/radarhere/Pillow/commit/58aa5f202f0e05481cc5d28dba7da3f5d8e0d337), the job [passes.](https://github.com/radarhere/Pillow/actions/runs/11479708265/job/31946563482)
If the only reason for removing the flag was that it is …
=> Restored `CMAKE_INSTALL_LIBDIR` to libjpeg-turbo

common_utils.sh
=> use musl libc 1.2 by default

common_utils.sh
I think this suggestion is self-explanatory.
=> Do not set MB_ML_VER on macOS

library_builders.sh
It looks like https://sourceforge.net/projects/libjpeg-turbo/files/ is no longer being updated - it only has version 3.0.1, while the latest version is 3.1.0.
So this switches the libjpeg-turbo URL to GitHub.
=> Updated libjpeg-turbo URL

library_builders.sh
Add `make -j4` to build more libraries in parallel.
This currently exists for some libraries,
https://github.com/multi-build/multibuild/blob/24f1446f6477893b2ef9d721aabcee7a494ca2b1/library_builders.sh#L386-L387
but not others.
https://github.com/multi-build/multibuild/blob/24f1446f6477893b2ef9d721aabcee7a494ca2b1/library_builders.sh#L363-L364
Furthers the work of https://github.com/multi-build/multibuild/pull/105
=> make with -j4
