multi-build/multibuild

appveyor.yml
ci/appveyor/install.ps1
ci/appveyor/missing-headers.ps1
ci/appveyor/windows_sdk.cmd

This can be used to build wheels in a conda enviroment on appveyor.
The tests use a simple package (origsel/python-appveyor-demo) to test
building and testing a wheel

Create appveyor framework with tests

---

library_builders.sh

Snappy is a compression/decompression library.

Add Snappy 1.1.3 builder.

---

library_builders.sh

LibLZF is a small compression library. Homepage:
http://oldhome.schmorp.de/marc/liblzf.html

Add LZF builder.

---

osx_utils.sh

echo status in repair_wheelhouse, avoid 10m limit

---

README.rst

This would address #34, but further details on how the AppVeyor system works would be welcome.

Briefly describe AppVeyor usage for Windows wheels

---

.travis.yml
docker_build_wrap.sh
manylinux_utils.sh
osx_utils.sh
travis_linux_steps.sh
travis_osx_steps.sh

File #44 against "devel" branch

---

library_builders.sh

Changed openjpeg directory prefix for versions newer than 2.1.0

---

library_builders.sh
tests/test_library_builders.sh

I have tested this and confirmed that it works.

ENH: libraries: add a build_github function

---

docker_build_wrap.sh
manylinux_utils.sh
osx_utils.sh

Unfortunately, after further testing, I found some errors that needed to be fixed.

Ccache: fixes

---

library_builders.sh
tests/test_library_builders.sh

Yields better performance on OSX

[library_builders] use brew to install openblas

---

tests/test_library_builders.sh
travis_osx_steps.sh
travis_steps.sh

[osx_steps] export cppflags

---

tests/test_library_builders.sh
travis_steps.sh

Reverts matthew-brett/multibuild#67

Revert "[osx_steps] export cppflags"

---

.travis.yml
osx_utils.sh

Closes #84.
Closes #75.
Closes #82.

Fix OSX failures

---

_gfortran_utils.sh
library_builders.sh
tests/test_library_builders.sh

/cc @matthew-brett 
This does not add time to existing builds and improves build time considerably for this function.
Closes #81.

Use a binary OpenBLAS

---

_gfortran_utils.sh
library_builders.sh

The archives directory was not created. I tested this downstream and the fix worked.

Fix OpenBLAS binary installation

---

library_builders.sh
tests/test_library_builders.sh

as requested in https://github.com/matthew-brett/multibuild/issues/92#issuecomment-351178130

library_builders: add libtool, ragel, flex and bison

---

common_utils.sh

See https://github.com/travis-ci/travis-ci/issues/8703#issuecomment-348866918

Disable pushd / popd wrappers

---

library_builders.sh

Reverts matthew-brett/multibuild#100
Netcdf was already present.

Revert "Libraries: add netcdf"

---

travis_linux_steps.sh

Reverts matthew-brett/multibuild#103

Revert "Customize Docker build image"

---

travis_linux_steps.sh

Reverts matthew-brett/multibuild#109

Revert "Merge master to devel"

---

README.rst
appveyor.yml
ci/appveyor/install.ps1
ci/appveyor/missing-headers.ps1
common_utils.sh

Updated URLs

---

README.rst

Addresses https://github.com/matthew-brett/multibuild/issues/38

Add notes clarifying what to check out

---

README.rst
docker_build_wrap.sh
travis_linux_steps.sh
travis_osx_steps.sh

Fixes part 2 of https://github.com/matthew-brett/multibuild/issues/116

Add config.pre to override envvars used in `library_builders.sh`

---

README.rst
configure_build.sh
docker_build_wrap.sh
library_builders.sh
tests/test_library_builders.sh
travis_osx_steps.sh
travis_steps.sh

Resolution option 2-1 for https://github.com/matthew-brett/multibuild/issues/116
Closes gh-129.

Split off build environment configuration to a dedicated file

---

configure_build.sh
library_builders.sh

From https://github.com/matthew-brett/multibuild/pull/130#issuecomment-360873994.

Library Builders: source configure_build

---

README.rst

DOC: some cleanup to README text

---

.travis.yml
tests/env_vars.sh
tests/test_multibuild.sh

[See for yourself](https://travis-ci.org/native-api/multibuild/jobs/332565592)

enable tracing for tests

---

common_utils.sh

See: https://github.com/pypa/manylinux/issues/160

BF: add back rsync, somehow removed from manylinux

---

common_utils.sh

Closes: https://github.com/matthew-brett/multibuild/issues/149
You can see the shorter log: https://travis-ci.org/cancan101/pyFFTW-wheels/jobs/350601191

Run rsync in non verbose mode

---

library_builders.sh

This is still WIP but am looking for feedback.

library_builders for fftw

---

common_utils.sh
tests/test_common_utils.sh

See: https://github.com/matthew-brett/multibuild/issues/166
Thanks to Andrew Murray for pointing out this bug.

MRG: fix and test is_function

---

.travis.yml
common_utils.sh
configure_build.sh
library_builders.sh
osx_utils.sh
tests/test_common_utils.sh
tests/test_fill_pypy_ver.sh
tests/test_library_builders.sh
tests/test_multibuild.sh
tests/test_python_install.sh
travis_linux_steps.sh

Proposing merge of the devel branch.
* Some library builders have been fixed, along with the library builder tests.
* Add build directory to PKG_CONFIG_PATH, fixes library finding for some libs.
* Add cfitsio builder (thanks Simon Conseil).
* Use HTTPS URLs for fetching archives where available (thanks Andrew Murray).
* Fixes to is_function to prevent executing tested-for function (thanks Andrew
Murray).
* Update manylinux URL to point to Rackspace, was pointing to Nipy server that
now has invalid certificate, and should be retired.

MRG: merge devel into master

---

common_utils.sh
tests/test_common_utils.sh

NF: add distutils platform check

---

README.rst

README: Add Python 3.7 for Travis CI

---

.travis.yml

You may wish to wait until Xcode 10 is out of beta, but the code change will be the same once it is out of beta.

Added Xcode 10 Travis build

---

.travis.yml
common_utils.sh
osx_utils.sh
tests/test_fill_pypy_ver.sh
tests/test_manylinux_utils.sh
tests/test_python_install.sh

Already dropped in https://github.com/matthew-brett/multibuild/pull/111.

Remove old code for EOL Python <= 2.6

---

tests/test_library_builders.sh
travis_linux_steps.sh

Cherry-picked the original commit from #196, and then I have made my own attempt at adding tests.

Pass MB_PYTHON_VERSION to docker run in build_multilinux

---

.travis.yml

Addresses https://github.com/matthew-brett/multibuild/pull/249#issuecomment-513490691

Use $PLAT default in tests

---

tests/test_multibuild.sh
travis_linux_steps.sh

Set defaults for PLAT where needed

Allow PLAT to be unset

---

.travis.yml
README.rst
configure_build.sh
tests/test_library_builders.sh
travis_linux_steps.sh

Add MB_ML_VER variable to choose Manylinux version.
Closes gh-238.

MRG: more explicit support for manylinux > 1

---

.appveyor.yml
.gitignore
install_python.ps1

hack at `install_python.ps1` to download the correct file

Add python 3.8.0rc1 to windows possibilities

---

.appveyor.yml
osx_utils.sh

CPython 3.8.0 was released
xref pypa/manylinux#370

CPython 3.8.0 was released

---

.appveyor.yml
install_python.ps1

The previous regexp did not work, and the script exited without complaining.
xref MacPython/numpy-wheels#66

Fix regexp and be more verbose

---

README.rst

mainly consolidating changes from https://github.com/matthew-brett/multibuild/pull/280 and https://github.com/matthew-brett/multibuild/pull/281

update README, mainly for macOS

---

common_utils.sh
library_builders.sh
manylinux_utils.sh
tests/test_common_utils.sh
tests/test_manylinux_utils.sh
tests/test_manylinux_utils_docker.sh
tests/test_multibuild.sh

A rebased and slightly edited version of #212 - with thanks.

MRG Ivan's changes from #212, rebased

---

supported_wheels.py

Fixes https://github.com/matthew-brett/multibuild/issues/298

supported_wheels.py: in pip 20, get_supported() returns list of Tags

---

common_utils.sh
tests/config.sh
tests/test_multibuild.sh
travis_linux_steps.sh

Replaces gh-315: rebased and fixed one more occurrence
Related to MacPython/pandas-wheels#79

Specify python, pip using PYTHON_EXE, PYTHON _EXE -mpip

---

common_utils.sh

Add pypy 7.3.1, released last week

---

README.rst

Appveyor has been removed in numpy/numpy#14711

Remove broken link to Numpy appveyor

---

README.rst

MRG: document switch from Rackspace

---

.travis.yml
osx_utils.sh
tests/test_osx_utils.sh

very minor changes over 2.7.17, but a couple are worth having for anyone still using 2.7
see https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.18rc1.rst

Update python 2.7 to 2.7.18

---

library_builders.sh

fixes gh-354 by updating the build_openblas function.

Update openblas download from anaconda

---

library_builders.sh

Fixes 6 of the jobs [currently failing in devel](https://travis-ci.org/github/matthew-brett/multibuild/builds/766300690)

Fixed hdf5 finding szip and libaec

---

osx_utils.sh

Minor cleanup. Only set a variable when it will be used.

Only determine py_osx_ver when necessary

---

README.rst
osx_utils.sh

https://github.com/matthew-brett/multibuild -> https://github.com/multi-build/multibuild

Update repo links

---

.appveyor.yml

Fix failing AppVeyor tests

---

osx_utils.sh

https://www.python.org/downloads/release/python-3912/

Updated Python versions

---

travis_linux_steps.sh

Updated to Alpine 3.16 test image after https://github.com/multi-build/docker-images/pull/34

Updated to Alpine 3.16 test image

---

README.rst

Docs: Add 3.10 to README

---

travis_linux_steps.sh

Updated to Alpine 3.17 test image after https://github.com/multi-build/docker-images/pull/38

Updated to Alpine 3.17 test image

---

README.rst

Updated Alpine Linux version in README

---

osx_utils.sh
tests/test_fill_pyver.sh

Python 3.12 beta 1 has been released - https://www.python.org/downloads/release/python-3120b1/

Added Python 3.12 beta

---

README.rst

README update after https://github.com/multi-build/docker-images/pull/38

Test images exist for arm64v8 Alpine Linux

---

README.rst
travis_linux_steps.sh

Updated Alpine Linux version

---

.github/workflows/lint_python.yml
.github/workflows/test.yml

actions/checkout v4 has been released - https://github.com/actions/checkout/releases/tag/v4.0.0

Updated actions/checkout to v4

---

.github/workflows/lint_python.yml
.github/workflows/test.yml

Also updates the Python version in the workflows to 3.12

Updated actions/checkout to v5
